### ISSUE TITLE
Concurrency labs

### ISSUE THREAD

**Issue by denyskonakhevych** [denyskonakhevych/Concurrency#1]
Dear Andrii,

Please, review results of my tasks.

Many thanks!

**Comment by arodionov** [comment]
- private class SeriesCounter - обратите внимание в чем отличие внутренних классов от внутренних статических классов
- class Bank
  Зачем запускать перевод денег в отдельном потоке? Сценарий использования метода transfer и так предполагает вызывать его в отдельном потоке (иначе нет смысла в обеспечении целостности транзакции)
- Общее замечание ко всему коду - в ряде мест сильно усложняете реализацию, что сильно сказывается на читабильность кода

**Comment by denyskonakhevych** [comment]
Тоесть для банка нужно сперва запустить поток, а в нем уже выполнить транзакцию?

**Comment by arodionov** [comment]
Смотрите, проблема заключается в том, что метод transfer могут вызывать одновременно несколько пользователей из разных потоков. Для банка никаких потоков создавать не надо

**Comment by denyskonakhevych** [comment]
Тоесть во внешнем потоке через экземпляр банка происходит вызов транзакции, которая выполняется через ExecutorService. Я явно никаких потоков не создаю.

**Comment by arodionov** [comment]
Еще раз.
Есть банк и следующий код
Bank bank = new Bank();
for (int i = 0; i<N; i++){
 new Thread( new Runnable(){
     bank.transfer(A, B, ammount);
   }
 ).start();
}

Зачем внутри банка ExecutorService и т.п.?

**Comment by denyskonakhevych** [comment]
Думал так Service сам подберет нужное количество потоков. И ещё это избавляет пользователя от необходимости создавать поток, джойнить его. Наверное я немного неправильно понял задание, переделаю. Извините, что столько вопросов задаю)

**Comment by denyskonakhevych** [comment]
Проверте, пожалуйста, этот вариант трансфера в банке
